# smile
heston_ranges:
  rho: [-0.15, 0.15]
  sigma: [0.5, 1.0]
  theta: [0.2, 0.5]
  kappa: [2.0, 3.0]
  v0: [0.1, 0.4]

grid:
  moneyness:
    start_point: 0.35
    step: 0.1
    end_point: 1.65

plot_surface:
  zlim: [0.0, 1.0]
